const $=id=>document.getElementById(id);
const PAGES=[['home','Home'],['rescue','AI Rescue'],['planner','Planner'],['doubt','Doubt Solver'],['notes','Notes'],['quiz','Quiz'],['readiness','Readiness'],['dashboard','Dashboard'],['resources','Resources'],['profile','Profile'],['about','About'],['contact','Contact']];
const TOP={'Data Structures':['Trees','Graphs','Sorting','Hashing'],'Mathematics':['Probability','Matrices','Calculus','Linear Algebra'],'DBMS':['Normalization','SQL Joins','Transactions','Indexing'],'Operating Systems':['CPU Scheduling','Deadlocks','Memory Management','Paging']};
const GEN=['Core concepts','Key methods & formulas','Problem practice','Previous-year questions'];
const BANK=[
['Data Structures','Trees','Maximum number of nodes at level k of a binary tree (root at level 0)?',['k','2k','2^k','2^(k+1)'],2,'Each level doubles the nodes, so level k has 2^k.'],
['Data Structures','Trees','Which traversal of a BST gives sorted order?',['Preorder','Inorder','Postorder','Level order'],1,'Inorder visits left, root, right — ascending in a BST.'],
['Data Structures','Sorting','Average time complexity of Quick Sort?',['O(n)','O(n log n)','O(n²)','O(log n)'],1,'Balanced partitions give n log n on average.'],
['Data Structures','Graphs','BFS uses which data structure?',['Stack','Queue','Heap','Tree'],1,'BFS explores level by level using a queue.'],
['Mathematics','Probability','Probability of getting a sum of 7 with two fair dice?',['1/6','1/12','5/36','7/36'],0,'6 favourable outcomes out of 36 = 1/6.'],
['Mathematics','Matrices','If det(A)=0 for a square matrix A, then A is…',['Invertible','Singular','Identity','Orthogonal'],1,'Zero determinant means no inverse: singular.'],
['Mathematics','Calculus','d/dx of sin(x²) is…',['cos(x²)','2x cos(x²)','2x sin(x²)','−cos(x²)'],1,'Chain rule: cos(x²)·2x.'],
['DBMS','Normalization','A relation is in 2NF if it is in 1NF and has no…',['Transitive dependency','Partial dependency','Multivalued dependency','Null values'],1,'2NF removes partial dependency on part of a composite key.'],
['DBMS','Transactions','Which ACID property ensures all-or-nothing execution?',['Consistency','Isolation','Atomicity','Durability'],2,'Atomicity: a transaction fully happens or not at all.'],
['DBMS','SQL Joins','Which join returns all rows from the left table even without matches?',['INNER','LEFT OUTER','CROSS','SELF'],1,'LEFT OUTER keeps all left rows, filling NULLs.'],
['Operating Systems','Deadlocks','Which is NOT a necessary condition for deadlock?',['Mutual exclusion','Hold and wait','Preemption','Circular wait'],2,'No preemption is required; preemption itself is not a condition.'],
['Operating Systems','CPU Scheduling','Which scheduling algorithm minimizes average waiting time (non-preemptive)?',['FCFS','SJF','Round Robin','Priority'],1,'Shortest Job First is optimal for average waiting time.']];
const PROBS=['My exam is very close','I have a lot of syllabus left',"I don't understand some topics","I don't know what to study first",'I am behind my study schedule','I need quick revision','I need help preparing for multiple subjects'];
const iso=d=>d.toISOString().slice(0,10);const addD=n=>{const d=new Date();d.setDate(d.getDate()+n);return d};
let S={demo:false,p:{name:'',course:'',year:'',prep:'',subs:'',goal:'',pref:''},exam:null,hrs:0,pct:0,subjects:[],tasks:[],goal:3,quizzes:[],notes:0,doubts:0,hoursDone:0,streak:0,plan:null,qs:null,ans:{}};
function loadDemo(){S.demo=true;S.p={name:'Aarav Sharma',course:'B.Tech Computer Science',year:'2',prep:'Moderate',subs:'Data Structures, Mathematics, DBMS, Operating Systems',goal:'Score 8+ CGPA this semester',pref:'Practice problems'};S.exam=iso(addD(12));S.hrs=5;S.pct=40;S.hoursDone=26;S.streak=5;S.notes=3;S.doubts=7;
S.subjects=[{n:'Data Structures',weak:1,strong:0,diff:1,done:35},{n:'Mathematics',weak:1,strong:0,diff:1,done:30},{n:'DBMS',weak:0,strong:1,diff:0,done:60},{n:'Operating Systems',weak:0,strong:0,diff:0,done:45}];
S.quizzes=[{s:'DBMS',pct:80,weak:[]},{s:'Data Structures',pct:50,weak:['Trees']}];S.tasks=[];
fill();$('dm').style.display='inline-block';buildPlan();tgDemo()}
function tgDemo(){$('dm').style.display=S.demo?'inline-block':'none'}
function fill(){$('r_name').value=S.p.name;$('r_course').value=S.p.course;$('r_year').value=S.p.year||'1';$('r_subs').value=S.p.subs;$('r_date').value=S.exam||'';$('r_prep').value=S.p.prep||'Moderate';$('r_pct').value=S.pct;$('r_hrs').value=S.hrs;$('r_weak').value=S.subjects.filter(x=>x.weak).map(x=>x.n).join(', ');$('r_strong').value=S.subjects.filter(x=>x.strong).map(x=>x.n).join(', ');$('r_meth').value=S.p.pref||'Reading notes';
['f_name','f_course','f_year','f_prep','f_subs','f_goal','f_pref'].forEach(k=>$(k).value=S.p[k.slice(2)]||'');$('f_year').value=S.p.year}
const cap=s=>s.trim();const list=s=>s.split(',').map(cap).filter(Boolean);
const daysLeft=()=>S.exam?Math.max(0,Math.ceil((new Date(S.exam+'T23:59:59')-new Date())/864e5)):0;
function subm(){const e=$('r_err');e.textContent='';const subs=list($('r_subs').value);
if(!$('r_name').value.trim())return e.textContent='Please enter your name.';
if(!subs.length)return e.textContent='Please select at least one subject.';
if(!$('r_date').value||new Date($('r_date').value+'T23:59:59')<new Date())return e.textContent='Please enter your exam date (it must be today or later).';
const pct=$('r_pct').value;if(pct===''||pct<0||pct>100)return e.textContent='Please enter the syllabus completed (0–100%).';
const h=+$('r_hrs').value;if(!h||h<0.5)return e.textContent='Please enter your available study hours per day.';
const weak=list($('r_weak').value).map(x=>x.toLowerCase()),str=list($('r_strong').value).map(x=>x.toLowerCase());
const old=Object.fromEntries(S.subjects.map(x=>[x.n.toLowerCase(),x.done]));
S.p={name:$('r_name').value.trim(),course:$('r_course').value.trim(),year:$('r_year').value,prep:$('r_prep').value,subs:subs.join(', '),goal:S.p.goal,pref:$('r_meth').value};
S.exam=$('r_date').value;S.hrs=h;S.pct=+pct;
S.subjects=subs.map(n=>({n,weak:weak.includes(n.toLowerCase())?1:0,strong:str.includes(n.toLowerCase())?1:0,diff:weak.includes(n.toLowerCase())?1:0,done:old[n.toLowerCase()]??Math.round(+pct)}));
S.rprobs=[...document.querySelectorAll('#r_probs input:checked')].map(i=>i.value);S.demo=S.demo&&false;tgDemo();fill();buildPlan(true);}
function score(x){return 3*x.weak+2*x.diff-2*x.strong+(100-x.done)/25+({Beginner:1,Moderate:.5,Good:0}[S.p.prep]||0)}
function buildPlan(show){const d=Math.max(1,daysLeft()),subs=[...S.subjects].sort((a,b)=>score(b)-score(a)),avail=d*S.hrs;
const need=subs.reduce((t,x)=>t+(100-x.done)/100*(x.diff||x.weak?14:9),0)+subs.length*1.5;
const ratio=avail/Math.max(need,1);const risk=ratio>=1.3&&d>3?'Low':ratio>=.9?'Medium':ratio>=.5?'High':'Critical';
const emergency=d<=5||ratio<.5||(S.rprobs||[]).includes('My exam is very close');
const topics=x=>(TOP[x.n]||GEN);const days=[];
const pool=[];subs.forEach(x=>{const w=x.weak?3:x.strong?1:2;const t=topics(x);let i=0;for(let k=0;k<w*2;k++)pool.push({s:x.n,t:t[(i++)%t.length],w:x.weak})});
const nd=Math.min(d,7);let pi=0;S.tasks=S.tasks.filter(t=>t.manual);
for(let i=0;i<nd;i++){const items=[];let left=S.hrs-0.5;const n=Math.max(1,Math.min(3,Math.round(S.hrs/1.5)));
for(let k=0;k<n;k++){const p=pool[pi++%pool.length];const h=Math.max(.5,Math.round(left/(n-k)*2)/2);left-=h;items.push({s:p.s,t:p.t,h});}
items.push({s:'Revision',t:'Recap of the day + 10 practice questions',h:.5});days.push({day:i+1,items});
items.forEach(it=>S.tasks.push({s:it.s,t:it.t,h:it.h,day:i,pr:'High',st:'Not Started'}));}
S.plan={d,avail:Math.round(avail),need:Math.round(need),risk,subs,days,emergency};
if(show)showPlan();syncSelects()}
const RC={Low:'#16a34a',Medium:'#d97706',High:'#ea580c',Critical:'#dc2626'};
function showPlan(){const P=S.plan;const rec={Low:'You are on track. Keep a steady pace and add mock tests in the last 3 days.',Medium:'Manageable if you stay consistent. Protect your daily hours and cover weak subjects first.',High:'Time is tight. Study weak, high-weight topics first and skip low-value details.',Critical:'You cannot cover everything. Follow the priority list strictly and use Emergency Mode.'}[P.risk];
$('r_out').innerHTML=`<div class="card" style="margin-top:16px"><p style="font-weight:700;font-size:18px">${P.emergency?'Don\'t panic. StudySOS has created your priority rescue plan.':'Good news, '+esc(S.p.name)+': you have a workable plan.'}</p>
<div class="grid"><div><div class="mu">Academic Risk Level</div><span class="risk" style="background:${RC[P.risk]}">${P.risk}</span><p>${rec}</p></div>
<div><div class="mu">Remaining study time</div><div class="big">${P.avail}h</div><div class="mu">${P.d} day(s) × ${S.hrs}h/day. Estimated need: ~${P.need}h</div><div class="bar"><i style="width:${Math.min(100,P.avail/Math.max(P.need,1)*100)}%"></i></div></div></div></div>
<div class="grid g2" style="margin-top:14px"><div class="card"><h3>Priority subjects</h3>${P.subs.map((x,i)=>`<div style="margin:8px 0"><b>${i+1}. ${esc(x.n)}</b> ${x.weak?'<span class="pill">Weak</span>':x.strong?'<span class="pill">Strong</span>':''}<div class="bar"><i style="width:${x.done}%"></i></div><small class="mu">${x.done}% covered</small></div>`).join('')}<p><b>Recommended study order:</b> ${P.subs.map(x=>esc(x.n)).join(' → ')}</p></div>
<div class="card"><h3>Daily rescue plan</h3>${P.days.map(d=>`<p><b>Day ${d.day}:</b></p><ul>${d.items.map(i=>`<li>${esc(i.s)} – ${esc(i.t)} – ${i.h} hour${i.h==1?'':'s'}</li>`).join('')}</ul>`).join('')}</div></div>
${P.emergency?'<div class="card" style="margin-top:14px;border:2px solid var(--bad)"><h3>🚨 Emergency Mode priorities</h3><ol><li>High-weight topics</li><li>Weak topics</li><li>Frequently tested concepts</li><li>Quick revision</li><li>Practice questions</li><li>Mock tests (last day)</li></ol></div>':''}
<div class="card" style="margin-top:14px"><b>Next steps:</b> <button class="btn" onclick="go('planner')">Open Study Planner</button><button class="btn s" onclick="go('doubt')">Ask a doubt</button><button class="btn s" onclick="go('notes')">Make notes</button><button class="btn s" onclick="go('quiz')">Take a quiz</button></div>`;}
function emerg(){const d=+$('e_d').value,s=+$('e_s').value,p=+$('e_p').value,h=+$('e_h').value,e=$('e_err');e.textContent='';
if(!d||d<1)return e.textContent='Please enter how many days are left.';if(!s)return e.textContent='Please enter how many subjects remain.';if(!p)return e.textContent='Please enter how much syllabus is incomplete.';if(!h)return e.textContent='Please enter your daily study hours.';
const tot=d*h,per=(tot/s).toFixed(1),names=S.subjects.length?[...S.subjects].sort((a,b)=>score(b)-score(a)).map(x=>x.n):Array.from({length:s},(_,i)=>'Subject '+(i+1));
const tl=[];for(let i=0;i<d;i++){const ph=i===d-1?'Final revision + mock test':i>=d-2&&d>2?'Practice questions & PYQs':i<Math.ceil(d/2)?'High-weight & weak topics':'Frequently tested concepts + quick notes';
tl.push(`<div><b>Day ${i+1}</b> – ${ph}<br><span class="mu">Focus: ${names.slice(0,s).map((n,k)=>(k+i)%Math.min(s,3)===0||s<=3?esc(n):'').filter(Boolean).slice(0,3).join(', ')||esc(names[0])} · ${h}h</span></div>`)}
$('e_out').innerHTML=`<div class="card" style="margin-top:14px;border:2px solid var(--bad)"><p class="err">⚠ Focus on high-priority topics first. Do not try to complete everything at once.</p><p>You have <b>${tot}h</b> total (~${per}h per subject) for <b>${p}%</b> of the syllabus remaining. Cover the top 40% highest-weight topics of each subject and drop deep-dive extras.</p><div class="tl">${tl.join('')}</div></div>`}
function esc(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function pTasks(){const t=S.tasks,done=t.filter(x=>x.st==='Completed').length,hrs=t.reduce((a,x)=>a+x.h,0),dh=t.filter(x=>x.st==='Completed').reduce((a,x)=>a+x.h,0);
$('pl_sum').innerHTML=[['Today\'s tasks',t.filter(x=>x.day===0&&x.st!=='Completed').length],['Upcoming',t.filter(x=>x.day>0&&x.st!=='Completed').length],['Completed',done],['Remaining',t.length-done],['Study hours',dh+'/'+hrs+'h'],['Progress',(t.length?Math.round(done/t.length*100):0)+'%']].map(a=>`<div class="card"><div class="mu">${a[0]}</div><div class="big">${a[1]}</div></div>`).join('')+`<div class="card"><div class="mu">Daily goal</div><div class="big">${S.goal}h</div></div>`;
const grp=(title,f)=>{const a=t.map((x,i)=>[x,i]).filter(f);return `<h3 style="margin-top:18px">${title} (${a.length})</h3>`+(a.map(([x,i])=>`<div class="card" style="margin:8px 0;display:flex;gap:10px;flex-wrap:wrap;align-items:center;justify-content:space-between"><div><b>${esc(x.s)}</b> – ${esc(x.t)} <span class="pill">${x.h}h</span> <span class="pill">${x.pr}</span> <small class="mu">${x.day===0?'Today':'Day +'+x.day}</small></div><select style="width:auto" onchange="setSt(${i},this.value)">${['Not Started','In Progress','Completed'].map(o=>`<option${o===x.st?' selected':''}>${o}</option>`).join('')}</select></div>`).join('')||'<p class="mu">Nothing here.</p>')};
$('pl_list').innerHTML=t.length?grp('Today',x=>x[0].day===0&&x[0].st!=='Completed')+grp('Upcoming',x=>x[0].day>0&&x[0].st!=='Completed')+grp('Completed',x=>x[0].st==='Completed'):'<div class="card" style="margin-top:14px">No tasks yet. <button class="btn" onclick="go(\'rescue\')">Create a rescue plan</button> or add one above.</div>'}
function setSt(i,v){const t=S.tasks[i];if(v==='Completed'&&t.st!=='Completed'){S.hoursDone+=t.h}else if(t.st==='Completed'&&v!=='Completed'){S.hoursDone-=t.h}t.st=v;
const sub=S.subjects.find(x=>x.n.toLowerCase()===t.s.toLowerCase());if(sub&&v==='Completed')sub.done=Math.min(100,sub.done+4);pTasks()}
function addT(){const s=$('p_s').value.trim(),t=$('p_t').value.trim(),h=+$('p_h').value,e=$('p_err');e.textContent='';if(!s)return e.textContent='Please enter a subject.';if(!t)return e.textContent='Please enter a topic.';if(!h)return e.textContent='Please enter study hours.';
S.tasks.push({s,t,h,day:+$('p_d').value||0,pr:$('p_p').value,st:'Not Started',manual:1});if(!S.subjects.find(x=>x.n.toLowerCase()===s.toLowerCase()))S.subjects.push({n:s,weak:0,strong:0,diff:0,done:0});$('p_s').value=$('p_t').value='';pTasks();syncSelects()}
function setGoal(){const g=prompt('Daily study goal (hours)?',S.goal);if(g&&+g>0){S.goal=+g;pTasks()}}
function syncSelects(){const o=(S.subjects.length?S.subjects.map(x=>x.n):Object.keys(TOP));$('d_s').innerHTML=o.map(x=>`<option>${esc(x)}</option>`).join('');const qo=[...new Set([...Object.keys(TOP)])];$('q_s').innerHTML=qo.map(x=>`<option>${x}</option>`).join('')}
async function ai(kind,p){return API.ai(kind,p,AIL)}
const AIL={doubt(p){const t=p.t||p.s,lv={Easy:'basics',Medium:'core ideas',Hard:'edge cases and proofs'}[p.l];
const mode={normal:'',simple:'Think of it like everyday life: ',ex:''}[p.mode]||'';
return{ex:`${mode}<b>${esc(t)}</b> in ${esc(p.s)} is about understanding the ${lv} behind your question: “${esc(p.q)}”. Break it into what is given, what is asked, and which rule connects them.`,
steps:['Restate the question in your own words and list what is given.','Identify the ${esc(t)} definition or rule that applies.'.replace('${esc(t)}',esc(t)),'Apply the rule step by step, writing each intermediate result.','Check the answer against a small example or boundary case.'],
eg:p.mode==='ex'?`Another example: take the smallest possible input for ${esc(t)} (size 1 or 2), solve it fully, then grow it by one element and see what changes.`:`Example: apply ${esc(t)} to a tiny case with 3 items and trace each step on paper.`,
key:`The key idea of ${esc(t)} is that a general rule can be reduced to a small repeatable procedure.`,mis:`Common mistake: jumping to the formula without checking the conditions under which it applies to ${esc(t)}.`,rev:`Revise: definition → one worked example → one exam-style question on ${esc(t)}.`}},
notes(p){const t=p.t,det=p.m==='Detailed Notes',q=p.m==='Quick Revision';return{Definition:`${t} (${p.s||'General'}) is a fundamental concept whose understanding is expected at ${p.d.toLowerCase()} level.`,'Important concepts':[`Core definition and terminology of ${t}`,`How ${t} is used to solve typical problems`,det?`Relationship of ${t} with neighbouring topics in ${p.s||'the subject'}`:'Where it appears in exams'],'Key points':q?[`${t}: remember definition, use-case, complexity/limits`]:[`State ${t} precisely before using it`,'Always list assumptions','Practise at least 5 varied problems'],Examples:[`Small worked example of ${t} with 3–4 inputs`],'Important formulas':[`Write down the standard formula/algorithm for ${t} on one line and memorise it`],'Common mistakes':['Mixing up similar terms','Skipping boundary cases','Not showing steps in written answers'],'Exam tips':['Start with the definition','Draw a neat diagram or table','Finish with a one-line conclusion'],'Quick revision summary':`${t}: define it → apply it → check it. Revisit in 1 day, 3 days and 7 days.`}}};
let lastQ=null;
async function solve(mode){const q=$('d_q').value.trim(),e=$('d_err');e.textContent='';if(mode==='normal'){if(!q)return e.textContent='Please type your question first.';lastQ={s:$('d_s').value,t:$('d_t').value.trim(),l:$('d_l').value,q}}if(!lastQ)return;
if(mode==='test'){S.qs=null;$('q_s').value=TOP[lastQ.s]?lastQ.s:'Data Structures';go('quiz');return}
const r=await ai('doubt',{...lastQ,mode});if(mode==='normal')S.doubts++;
$('d_out').innerHTML=`<div class="card" style="margin-top:14px"><div class="mu">🤖 StudySOS AI</div><h3>1. Simple explanation</h3><p>${r.ex}</p><h3>2. Step-by-step solution</h3><ol>${r.steps.map(s=>'<li>'+s+'</li>').join('')}</ol><h3>3. Example</h3><p>${r.eg}</p><h3>4. Key concept</h3><p>${r.key}</p><h3>5. Common mistake</h3><p>${r.mis}</p><h3>6. Quick revision point</h3><p>${r.rev}</p><button class="btn s" onclick="solve('simple')">Explain More Simply</button><button class="btn s" onclick="solve('ex')">Give Me an Example</button><button class="btn" onclick="solve('test')">Test Me on This Topic</button></div>`}
let notesTxt='';
async function notes(){const t=$('n_t').value.trim(),e=$('n_err');e.textContent='';if(!t)return e.textContent='Please enter a topic.';
const n=await ai('notes',{t,s:$('n_s').value.trim(),m:$('n_m').value,d:$('n_d').value});S.notes++;
notesTxt=`${t.toUpperCase()} – ${$('n_m').value}\n\n`+Object.entries(n).map(([k,v])=>`${k}\n${Array.isArray(v)?v.map(x=>'• '+x).join('\n'):v}`).join('\n\n');
$('n_out').innerHTML=`<div class="card" style="margin-top:14px">${Object.entries(n).map(([k,v])=>`<h3>${k}</h3>${Array.isArray(v)?'<ul>'+v.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>':'<p>'+esc(v)+'</p>'}`).join('')}<button class="btn" onclick="cpN()">Copy notes</button><button class="btn s" onclick="dlN()">Download .txt</button></div>`}
function cpN(){navigator.clipboard?.writeText(notesTxt).then(()=>alert('Notes copied!'),()=>alert('Copy blocked by the browser. Use Download instead.'))||alert('Use Download instead.')}
function dlN(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([notesTxt],{type:'text/plain'}));a.download='studysos-notes.txt';a.click()}
async function mkQuiz(){const s=$('q_s').value,n=+$('q_n').value,e=$('q_err');e.textContent='';let b=BANK.filter(x=>x[0]===s);if(!b.length)return e.textContent='Please select a subject.';
b=[...b].sort(()=>Math.random()-.5);while(b.length<n&&b.length<BANK.length)b.push(...BANK.filter(x=>x[0]!==s).slice(0,n-b.length));S.qs=(await API.quiz(s,n,$('q_d').value))||{s,q:b.slice(0,n)};S.ans={};drawQ()}
function drawQ(r){const Q=S.qs;$('q_out').innerHTML=`<div class="card" style="margin-top:14px">${Q.q.map((x,i)=>`<p><b>Q${i+1}. ${esc(x[2])}</b> <span class="pill">${x[1]}</span></p>${x[3].map((o,j)=>`<label class="opt ${r?(j===x[4]?'c':S.ans[i]===j?'w':''):''}"><input type="radio" name="q${i}" ${S.ans[i]===j?'checked':''} ${r?'disabled':''} onchange="S.ans[${i}]=${j}"> ${esc(o)}</label>`).join('')}${r?`<p class="mu">💡 ${esc(x[5])}</p>`:''}`).join('')}${r?'':'<div id="qe" class="err"></div><button class="btn" onclick="subQ()">Submit quiz</button>'}</div>${r||''}`}
function subQ(){const Q=S.qs;if(Object.keys(S.ans).length<Q.q.length){$('qe').textContent='Please answer every question before submitting.';return}
let c=0;const weak=[];Q.q.forEach((x,i)=>{if(S.ans[i]===x[4])c++;else weak.push(x[1])});const pct=Math.round(c/Q.q.length*100);
S.quizzes.push({s:Q.s,pct,weak});API.attempt({s:Q.s,pct,weak});const fb=pct>=80?'Excellent preparation':pct>=60?'Good, but revise weak areas':pct>=40?'More practice recommended':'Focus on fundamentals first';
const res=`<div class="card" style="margin-top:14px"><div class="big">${c}/${Q.q.length} · ${pct}%</div><p><b>${fb}</b></p><p>✅ Correct: ${c} · ❌ Incorrect: ${Q.q.length-c}</p><p><b>Weak areas:</b> ${[...new Set(weak)].join(', ')||'None 🎉'}</p><p><b>Recommended revision:</b> ${[...new Set(weak)].map(w=>w+' (45 min)').join(', ')||'Keep practising mixed questions'}</p><button class="btn" onclick="go('dashboard')">See updated progress</button><button class="btn s" onclick="go('readiness')">Exam readiness</button></div>`;drawQ(res)}
function stats(){const sub=S.subjects,avg=sub.length?Math.round(sub.reduce((a,x)=>a+x.done,0)/sub.length):0,qa=S.quizzes.length?Math.round(S.quizzes.reduce((a,x)=>a+x.pct,0)/S.quizzes.length):0;
const days=daysLeft(),need=S.plan?S.plan.need:1,rev=Math.min(100,Math.round(S.hoursDone/Math.max(need,1)*100));
const ready=Math.round(.4*avg+.25*qa+.2*Math.min(100,rev)+.15*Math.min(100,S.streak*14));return{avg,qa,days,rev,ready:Math.min(100,ready)}}
function recs(){const st=stats(),r=[];S.quizzes.forEach(q=>q.weak.forEach(w=>{const m=`You are weak in ${w}. Spend 45 minutes revising this topic.`;if(!r.includes(m))r.push(m)}));
const best=S.quizzes.filter(q=>q.pct>=70).pop();if(best)r.push(`Your quiz performance in ${best.s} is strong (${best.pct}%). Keep it warm with a short weekly review.`);
if(S.exam&&st.days<=7)r.push('You have limited time before your exam. Prioritize important topics.');
const w=S.subjects.filter(x=>x.weak).map(x=>x.n);if(w.length)r.push(`Focus on ${w.join(' and ')} before beginning final revision.`);
const td=S.tasks.filter(x=>x.day===0);if(td.length&&td.every(x=>x.st==='Completed'))r.push("You completed today's goal. Continue tomorrow to maintain your streak.");
if(!r.length)r.push('Create a rescue plan to receive personalized recommendations.');return r}
function rd(){const st=stats(),P=S.plan;if(!S.subjects.length){$('rd').innerHTML='<div class="card">No data yet. <button class="btn" onclick="loadDemo();go(\'readiness\')">Load demo student</button> or <button class="btn s" onclick="go(\'rescue\')">start a rescue</button>.</div>';return}
const col=st.ready>=70?'var(--ok)':st.ready>=45?'var(--wa)':'var(--bad)';const C=2*Math.PI*54;
$('rd').innerHTML=`<div class="grid g2"><div class="card" style="text-align:center"><svg viewBox="0 0 140 140" width="180"><circle cx="70" cy="70" r="54" fill="none" stroke="var(--pr2)" stroke-width="14"/><circle cx="70" cy="70" r="54" fill="none" stroke="${col}" stroke-width="14" stroke-linecap="round" stroke-dasharray="${C*st.ready/100} ${C}" transform="rotate(-90 70 70)"/><text x="70" y="78" text-anchor="middle" font-size="28" font-weight="800" fill="var(--tx)">${st.ready}</text></svg><div class="big">Exam Readiness: ${st.ready}%</div></div>
<div class="card"><p>⏳ Countdown: <b>${S.exam?st.days+' days':'Not set'}</b></p><p>📘 Syllabus completion: <b>${st.avg}%</b></p><p>🕒 Study hours completed: <b>${S.hoursDone}h</b></p><p>📝 Quiz performance: <b>${st.qa}%</b></p><p>🔁 Revision status: <b>${st.rev}%</b></p><p>💪 Strong: ${S.subjects.filter(x=>x.strong).map(x=>esc(x.n)).join(', ')||'—'}</p><p>⚠ Weak: ${S.subjects.filter(x=>x.weak).map(x=>esc(x.n)).join(', ')||'—'}</p></div></div>
<div class="card" style="margin-top:14px"><h3>AI recommendations</h3><ul>${recs().map(x=>'<li>'+esc(x)+'</li>').join('')}</ul></div>`}
function dash(){const st=stats();if(!S.subjects.length){$('db').innerHTML='<div class="card">No data yet. <button class="btn" onclick="loadDemo();go(\'dashboard\')">Load demo student</button></div>';return}
const ach=[['First Study Session',S.hoursDone>0],['First Quiz',S.quizzes.length>0],['5 Topics Completed',S.tasks.filter(x=>x.st==='Completed').length>=5],['10 Questions Solved',S.quizzes.length*5+S.doubts>=10],['7-Day Study Streak',S.streak>=7]];
const comp=S.tasks.filter(x=>x.st==='Completed').length;
$('db').innerHTML=`<div class="card"><h3>Overall academic progress: ${st.avg}%</h3><div class="bar"><i style="width:${st.avg}%"></i></div></div>
<div class="grid" style="margin-top:14px">${[['Total study hours',S.hoursDone+'h'],['Weekly study hours',Math.min(S.hoursDone,S.hrs*7)+'h'],['Topics completed',comp],['Quizzes attempted',S.quizzes.length],['Avg quiz score',st.qa+'%'],['Notes generated',S.notes],['Doubts solved',S.doubts]].map(a=>`<div class="card"><div class="mu">${a[0]}</div><div class="big">${a[1]}</div></div>`).join('')}</div>
<h3 style="margin-top:18px">Subject progress</h3><div class="grid">${S.subjects.map(x=>{const tp=(TOP[x.n]||GEN).length,dn=Math.round(x.done/100*tp);return`<div class="card"><b>${esc(x.n)}</b> <span class="pill">${x.strong?'Strong':x.weak?'Needs work':'Average'}</span><div class="bar" style="margin:8px 0"><i style="width:${x.done}%"></i></div>${x.done}% · ${dn} topics done · ${tp-dn} remaining</div>`}).join('')}</div>
<div class="grid g2" style="margin-top:14px"><div class="card"><h3>🔥 Current Study Streak: ${S.streak} Days</h3><div class="cal">${Array.from({length:14},(_,i)=>`<div class="${i>=14-S.streak?'f':''}">${i+1}</div>`).join('')}</div><p class="mu">Study a little every day — consistency beats cramming.</p></div>
<div class="card"><h3>🏆 Achievements</h3>${ach.map(a=>`<p>${a[1]?'✅':'🔒'} ${a[0]}</p>`).join('')}</div></div>
<div class="card" style="margin-top:14px"><h3>AI study recommendations</h3><ul>${recs().map(x=>'<li>'+esc(x)+'</li>').join('')}</ul></div>`}
const RES={'Study Materials':[['NPTEL lecture courses','https://nptel.ac.in'],['MIT OpenCourseWare','https://ocw.mit.edu']],'Revision Resources':[['One-day revision checklist','Review definitions → solved examples → past questions.'],['Spaced repetition: review at 1, 3, 7 days','']],'Practice Questions':[['GeeksforGeeks practice','https://www.geeksforgeeks.org'],['Previous-year papers: ask your department office','']],'Important Topics':[['Data Structures: Trees, Graphs, Sorting',''],['DBMS: Normalization, Transactions, SQL',''],['OS: Scheduling, Deadlocks, Memory','']],'Formula Sheets':[['Probability: P(A∪B)=P(A)+P(B)−P(A∩B)',''],['Master theorem for recurrences',''],['Sum of n terms: n(n+1)/2','']],'Exam Tips':[['Attempt easy questions first',''],['Write definitions before explanations',''],['Reserve the last 10 minutes to review','']],'Learning Resources':[['Khan Academy','https://www.khanacademy.org'],['3Blue1Brown (maths intuition)','https://www.youtube.com/@3blue1brown']]};
function saveProf(){const g=k=>$('f_'+k).value.trim();if(!g('name'))return $('f_msg').textContent='Please enter your name.';
Object.assign(S.p,{name:g('name'),course:g('course'),year:g('year'),prep:g('prep'),subs:g('subs'),goal:g('goal'),pref:g('pref')});
const ns=list(S.p.subs);ns.forEach(n=>{if(!S.subjects.find(x=>x.n.toLowerCase()===n.toLowerCase()))S.subjects.push({n,weak:0,strong:0,diff:0,done:0})});$('f_msg').textContent='Profile saved ✔';fill();syncSelects()}
async function contact(){const e=$('c_err');e.textContent='';if(!$('c_n').value.trim())return e.textContent='Please enter your name.';if(!/\S+@\S+\.\S+/.test($('c_e').value))return e.textContent='Please enter a valid email address.';if(!$('c_m').value.trim())return e.textContent='Please write your message.';
const ok=await API.feedback({name:$('c_n').value.trim(),email:$('c_e').value.trim(),message:$('c_m').value.trim()});e.style.color=ok?'var(--ok)':'var(--bad)';e.textContent=ok?'Thank you! Your feedback has been recorded.':'Could not send feedback right now. Please try again.';if(!ok)return;$('c_m').value=''}
function go(id){document.querySelectorAll('section').forEach(s=>s.classList.toggle('on',s.id===id));document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('on',a.dataset.p===id));document.getElementById('nav').classList.remove('open');
if(id==='planner')pTasks();if(id==='readiness')rd();if(id==='dashboard')dash();if(id==='home'||id==='emergency'){}if(id==='emergency'&&S.exam){$('e_d').value=daysLeft()||'';$('e_s').value=S.subjects.length||'';$('e_p').value=100-S.pct;$('e_h').value=S.hrs}
history.replaceState(null,'','#'+id);scrollTo({top:0,behavior:'smooth'})}
function tg(){const r=document.documentElement,d=getComputedStyle(r).getPropertyValue('--bg').trim()==='#0e1422';r.dataset.theme=d?'light':'dark'}
$('nav').innerHTML=PAGES.map(p=>`<a data-p="${p[0]}" onclick="go('${p[0]}')">${p[1]}</a>`).join('')+'<a data-p="emergency" onclick="go(\'emergency\')" style="color:var(--bad)">🚨 Emergency</a>';
$('probs').innerHTML=['Too much syllabus','Too little time',"Don't know where to start",'Difficult topics','Exam anxiety','Poor revision','No proper study plan'].map(x=>`<div class="card">😟 <b>${x}</b></div>`).join('');
$('feats').innerHTML=[['rescue','🆘','AI Academic Rescue','Risk level, priorities and a day-by-day plan.'],['planner','📅','Smart Study Planner','Track tasks, hours and daily goals.'],['doubt','💬','AI Doubt Solver','Six-part structured explanations.'],['notes','📝','AI Notes Generator','Exam-oriented notes, copy or download.'],['quiz','🧪','AI Quiz Generator','MCQs with score and weak-area analysis.'],['readiness','🎯','Exam Readiness','A 0–100 readiness score and advice.'],['dashboard','📊','Progress Dashboard','Stats, streaks and achievements.'],['emergency','🚨','Emergency Mode','Compressed plan when the exam is days away.']].map(f=>`<div class="card" style="cursor:pointer" onclick="go('${f[0]}')"><div style="font-size:26px">${f[1]}</div><h3>${f[2]}</h3><span class="mu">${f[3]}</span></div>`).join('');
$('r_probs').innerHTML=PROBS.map(p=>`<label class="chk"><input type="checkbox" value="${p}"> ${p}</label>`).join('');
$('resg').innerHTML=Object.entries(RES).map(([k,v])=>`<div class="card"><h3>${k}</h3>${v.map(([a,b])=>b.startsWith('http')?`<p><a class="res" href="${b}" target="_blank" rel="noopener">${a} ↗</a></p>`:`<p>• ${a}${b?'<br><span class="mu">'+b+'</span>':''}</p>`).join('')}</div>`).join('');
syncSelects();
API.load().then(st=>{if(st&&st.subjects&&st.subjects.length){Object.assign(S,st);fill()}else{loadDemo();S.demo=true}tgDemo();syncSelects();route()});
setInterval(()=>API.save(S),3000);
function route(){const h=location.hash.slice(1);go(PAGES.some(p=>p[0]===h)||h==='emergency'?h:'home')}
route();
